server:
  port: 8000
spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/lakeSide_hotel_db
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      format_sql: true
#      dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB
